export const DATABASE_ID = process.env.NEXT_PUBLIC_APPWRITW_DATABASE_ID;
export const WORKSPACES_ID = process.env.NEXT_PUBLIC_APPWRITW_WROKSPACES_ID;
export const IMAGES_BUCKET_ID = process.env.NEXT_PUBLIC_APPWRITW_IMAGES_BUCKET;
export const MEMBERS_ID = process.env.NEXT_PUBLIC_APPWRITW_MEMBERS_ID;
export const PROJECTS_ID = process.env.NEXT_PUBLIC_APPWRITW_PROJECTS_ID;
